### ISSUE TITLE
Fatal error with bf_form_ellement_accordion_start() and bf_form_ellement_accordion_end()

### ISSUE THREAD

**Issue by vinylroads** [BuddyForms/BuddyForms-ACF#1]
Hi,

I’ve bought BuddyForms ans some add-ons. I was trying this new plugin as i am really interseted to add ACF field to BuddyForms.

However, i have a fatal error in admin/buddyform after installing the plugin :

    Fatal error: Call to undefined function bf_form_ellement_accordion_start() in /Users/Home/Dev/laplateforme/app/plugins/BuddyForms-ACF-master/includes/form-elements.php on line 11

Il i comment this line, i got the same erreor on line 16 (bf_form_ellement_accordion_end() )

If i comment this line again, i can access to buddyform.

**Comment by svenl77** [comment]
Hi @vinylroads ,

thanks for your feedback.
This extension is in development right now and only works with the upcoming version of BuddyForms.

I have rebuild the BuddyForms Admin UI to make it much easier to extend for other developers.

The ACF Extension will be released after the new BuddyForms version. We should have something ready by the beginning of next week.

Cheers,
Sven

**Comment by vinylroads** [comment]
Thanks for your answer. I’m ready to test it !

The plugin will support all ACF Field Types (like relationship, true false, etc) ?

**Comment by svenl77** [comment]
Yes, it will support all ACF features. What you see now was just a test. Wait for the first beta for your testing.

I will update you in the ticket. Thanks for your help ;)

**Comment by svenl77** [comment]
Hi @vinylroads we are ready for testing.
